project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Introduction to Microeconomics: Lecture Notes"
  author:
    - name: Udayan Roy
      email: udayan.roy@liu.edu
  repo-url: https://github.com/UdayanRoy62/intromicro
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - introduction.qmd
    - trade.qmd
    - supply_demand.qmd
    - elasticity.qmd
    - supply_demand_government.qmd
    - welfare.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 4
    link-external-newwindow: true
  pdf:
    documentclass: book
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

