# Introduction to Economics  {#sec-introduction}

## Chapter Outline

-   What is economics?

-   What is the use of economics?

-   What are economists expected to do?

-   How do economists do what they are expected to do?

-   Why does the economist’s method sometimes fail?

-   What is macroeconomics?

-   What is microeconomics?

## What is Economics?

Economics is the study of our responses to scarcity, and the consequences of those responses.

Scarcity – in economics – is the fact that we can’t always get what we want.

None of us has Aladdin’s magic lamp.

## What is the Use of Economics?

Scarcity compels us to come up with less wasteful ways of running our societies.

We all want progress, and we all want to reduce hunger, poverty and inequality. But our resources are finite. Therefore, we can’t afford to run our societies in wasteful and inefficient ways. That’s where good economic policies have a crucial role to play. That’s where the economist can contribute.

The goals of a nation should not be set by economists. In democracies, it is usually the job of the elected representatives of the people to determine the nation’s goals. Once the goals have been determined, it is the job of the economist to outline the various policies by which the nation’s goals may be reached (assuming the goals are reachable).

The economist must also predict the likely benefits and costs of each of the various policies by which the nation’s goals may be achieved.

The people’s representatives can then pick the policy they like best.

### Wasted Resources: Stuck in Traffic 

We waste a lot of time stuck in traffic. Economists would want to find a way to reduce this waste of time. Building more roads may not always be possible, may not solve the problem, and may be costly in any case. Charging car owners for the use of a road may be the way to go. Investing in or subsidizing public transport is another option.

#### Wasted Resources: Stuck in Traffic: News Item

[Charging Drivers for Road Use Is Popular With Economists, Less So With Drivers](https://www.wsj.com/articles/charging-drivers-for-road-use-is-popular-with-economists-less-so-with-drivers-11630245780) By David Harrison, The Wall Street Journal, Aug. 29, 2021

### Wasted Resources: Unemployment 

What can we do to reduce this waste of resources? Cut taxes to encourage people to go shopping? Have the government spend more roads and bridges? Make overtime work illegal? Limit imports?

### Wasted Resources: Environment Destruction

How can we ensure that the resources that sustain life on this planet are conserved?

### Addressing Ethical Imperatives: Health Care

How can we ensure that people do not need to worry about something as basic as healthcare?

### Addressing Ethical Imperatives: Inequality 

How can we ensure that incomes are more equally shared?

This assumes that a more equal nation is what the people want. (Remember that it is not the economist’s job to say what the nation should or should not want.) Raise taxes on the rich? Invest in and subsidize higher education? Change existing laws to strengthen labor unions?

### Addressing Ethical Imperatives: Intergenerational Mobility

How can we keep the American Dream—the idea that each generation lives better than their parents—alive? Universal Basic Income? Baby Bonds? Require politicians to raise election campaign money through small donations? Tuition-free college?

## What Are Economists Expected to Do? 

As we have just seen, when asked specific policy-related questions, the economist has to think hard and:

-   Identify the list of the options available to society, and

-   Make predictions of the consequences—costs and benefits—that would follow from each of those options.

The democratic process must then decide which option to pursue.

### Government policies can make a difference: in ways good and bad: Examples

Government’s Pandemic Response Turned a Would-Be Poverty Surge Into a Record Poverty Decline, By Danilo Trisi, Center for Budget and Policy Priorities, August 29, 2023

#### When Economic Policies Go Wrong: Joseph Stalin 

Clearly, the stakes are very high in getting our economic policies right. The Soviet leader Stalin is believed to have caused about 40 million deaths during the 1930s in the then Soviet Union in an attempt to collectivize agriculture. For more on Stalin’s policies and their effects see:

-   *Harvest of Sorrow: Soviet Collectivization and the Terror-Famine* by Robert Conquest, Oxford University Press, New York, NY, 1986, ISBN 0195051807.

-   *Bloodlands: Europe Between Hitler and Stalin* by Timothy Snyder, Basic Books, New York, NY, 2010, ISBN 978-0465002399.

#### When Economic Policies Go Wrong—Mao Zedong

During 1958-61 there was a famine in China that is estimated to have killed 30 million people. Those deaths were largely due to the Chinese leader Mao Zedong’s failed economic policy—grandly called “the great leap forward”—of the forced industrialization of China’s agricultural economy.

For more on Mao’s policies and the famine that they caused please read:

-   Tombstone: The Great Chinese Famine, 1958-1962 by Yang Jisheng, Farrar, Straus and Giroux, New York, NY, 2012, ISBN 978-0374277932.

-   Hungry Ghosts: Mao’s Secret Famine by Jasper Becker, Free Press, New York, NY, 1996, ISBN: 068483457X.

-   Mao’s Great Famine: The History of China’s Most Devastating Catastrophe by Frank Dikotter, Walker & Co., New York, NY, 2010, ISBN: 978-0-8027-7768-3.

## How Do Economists Do What They Are Expected to Do? 

### Economists make simplifying assumptions

The simplifications help economists make predictions about the likely consequences of different policy options.

Economists usually disagree about their predictions. This is because different economists make different simplifying assumptions.

They try to use data to sort out their disagreements. If all goes well, economists may come up with unambiguous and useful advice for policy makers.

An actual economy is extremely complex. So, it is hard to think about how it would respond to, say, an increase in income tax rates. Therefore, it would be hard to make even a theoretical prediction of a tax hike’s effect on, say, the unemployment rate.[^introduction-1] So economists need to make simplifying assumptions in their analyses. They need to imagine a simpler economy because it might be easier to make a prediction for the simplified imaginary economy than for the complex actual economy.

[^introduction-1]: Remember, this is the sort of prediction that the nation might need.

These simplifying assumptions must be very carefully chosen, however, so that the hypothetical simplified economy is not too dissimilar to the actual economy, and is, at the same time, easier to analyze than the actual economy.

#### Predictions: Examples 

-   If income tax rates are increased, the nation’s unemployment rate will increase.

-   If Florida has a severe winter, the price of orange juice will increase.

-   If the price of imported oil goes up, the nation’s gross domestic product will decrease.

-   If the tax per airline ticket is increased, the price of hotel rooms will decrease.

#### Predictions: Disagreements Are Inevitable 

There is no universally accepted way for economists to decide which simplifying assumptions are the most appropriate. Different economists when asked the same question—say, How will an income tax hike affect unemployment?—may make different simplifying assumptions in their analyses. Therefore, they may end up making different predictions.

#### Data Helps to Sort Out Disagreements 

When economists disagree, the right kind of historical evidence may help them decide which economist’s prediction to trust. A large part of the economist’s job is to dig up evidence from the past, and use the evidence to test the clashing theories that various economists may propose.

## Why Does the Economist’s Method Sometimes Fail? 

We have just seen that different economists may give different answers (predictions) for the same question. Those disagreements can’t always be sorted out. (Why?) This leaves the general public puzzled and annoyed.

### Economists’ Disagreements Can’t Always Be Sorted Out 

Often there isn’t enough data. When there isn't enough data, one may not be able to choose between clashing theories or predictions.

Economists generally can’t do experiments. Even if there is a lot of historical data, there is no guarantee that a study of the past will help in identifying the best theory or prediction. If you toss a coin ten thousand times, you would be no better at predicting the ten thousand and first toss as you were at predicting the first toss.

## What Is Macroeconomics? What Is Microeconomics? 

Macroeconomics deals with questions about variables that describe the economy of an entire nation. Microeconomics deals with questions related to individual economic agents, such as households and firms.

### Macroeconomics 

Macroeconomics deals with issues related to data that give summary descriptions of the economy of an entire nation. A macroeconomist would ponder questions such as: What would happen to Uzbekistan’s unemployment rate if Japan suddenly stops trading with Uzbekistan and what policy should the government of Uzbekistan then follow? The focus would always be on Uzbekistan as a whole.

### Microeconomics 

Microeconomics deals with questions related to economic variables that describe a sub-national entity, typically individual economic agents, such as households and firms.

### Macro and Micro Are Related 

One cannot really do macroeconomics without simultaneously doing microeconomics. One cannot analyze an economy without studying the behavior of the individual economic units that make up that economy.

Conversely, the decisions by individuals are often guided by their expectations about incomes, interest rates, inflation, and the like. And these expectations cannot be understood without an analysis of the economy as a whole.

However, in macroeconomics the microeconomic underpinnings are de-emphasized. Conversely, in microeconomics the macroeconomic foundations of people's expectations are de-emphasized.

This course focuses on microeconomics.
